---
- name: Configure EC2 instance
  hosts: ec2_instances
  become: yes
  vars:
    java_version: "openjdk-11-jdk"
    jenkins_version: "2.289.1"
    sonarqube_version: "8.9.0.43852"
    
  roles:
    - git
    - docker
    - java
    - jenkins
    - sonarqube
    - environment
